require_relative './db/db'

connection = ActiveRecord::Base.connection

# TABLE operacoes
connection.execute("CREATE TABLE
  `operacoes` (
    `id` int NOT NULL AUTO_INCREMENT,
    `codigo_filial` varchar(5) NOT NULL,
    `sequencia` int NOT NULL,
    `tipo` varchar(4) NOT NULL,
    `data_gravacao` date DEFAULT NULL,
    `data_efetivacao` date NOT NULL,
    `data_aut_doc_fiscal` date DEFAULT NULL,
    `mes_efetivacao` varchar(10) NOT NULL,
    `codigo_vendedor` int NOT NULL,
    `nome_vendedor` varchar(100) DEFAULT NULL,
    `codigo_cliente` int DEFAULT NULL,
    `nome_cliente` varchar(100) DEFAULT NULL,
    `codigo_produto` varchar(12) NOT NULL,
    `ean` varchar(15) DEFAULT NULL,
    `nome_produto` varchar(120) NOT NULL,
    `fornecedor_1` varchar(100) DEFAULT NULL,
    `fornecedor_2` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
    `fornecedor_3` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
    `fornecedor_4` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
    `fornecedor_5` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
    `fabricante` varchar(50) DEFAULT NULL,
    `codigo_classe` int NOT NULL,
    `nome_classe` varchar(25) NOT NULL,
    `codigo_familia` int DEFAULT NULL,
    `familia` varchar(50) DEFAULT NULL,
    `quantidade` int DEFAULT NULL,
    `tabela_venda` varchar(20) DEFAULT NULL,
    `tabela_comparativa_1` varchar(20) DEFAULT NULL,
    `tabela_comparativa_2` varchar(20) DEFAULT NULL,
    `preco_unitario` decimal(8, 2) NOT NULL,
    `valor_desconto` decimal(8, 2) NOT NULL DEFAULT '0.00',
    `percentual_desconto` decimal(7, 4) NOT NULL DEFAULT '0.0000',
    `valor_item_final` decimal(8, 2) NOT NULL,
    `valor_total_final` decimal(8, 2) DEFAULT NULL,
    `custo_item` decimal(8, 2) NOT NULL DEFAULT '0.00',
    `custo_total` decimal(8, 4) DEFAULT NULL,
    `markup_produto` decimal(7, 4) NOT NULL DEFAULT '0.0000',
    `markup_venda` decimal(7, 4) DEFAULT NULL,
    `margem_contribuicao_produto` decimal(8, 2) NOT NULL,
    `margem_contribuicao_venda` decimal(8, 2) DEFAULT NULL,
    `forma_recebimento` varchar(150) DEFAULT NULL,
    `quantidade_parcelas` int DEFAULT NULL,
    PRIMARY KEY (`id`)
  )")


# TABLE produtos
connection.execute("CREATE TABLE
  `produtos` (
    `id` int NOT NULL AUTO_INCREMENT,
    `codigo` varchar(12) NOT NULL,
    `nome` varchar(250) NOT NULL,
    `classe` varchar(25) NOT NULL,
    `marca` varchar(50) NOT NULL,
    `modelo` varchar(100) DEFAULT NULL,
    `tipo_lente` varchar(50) DEFAULT NULL,
    `indice` varchar(25) DEFAULT NULL,
    `tratamento_foto` varchar(25) DEFAULT NULL,
    `tratamento_ar` varchar(25) DEFAULT NULL,
    `variacao_ar` varchar(25) DEFAULT NULL,
    `esferico` decimal(4, 2) DEFAULT NULL,
    `cilindrico` decimal(4, 2) DEFAULT NULL,
    `eixo` int DEFAULT NULL,
    PRIMARY KEY (`id`)
  )")

# TABLE resultados
connection.execute("CREATE TABLE
  `resultados` (
    `id` int NOT NULL AUTO_INCREMENT,
    `codigo_filial` varchar(5) CHARACTER SET utf8mb4 NOT NULL,
    `sequencia` int NOT NULL,
    `tipo` varchar(4) CHARACTER SET utf8mb4 NOT NULL,
    `data_gravacao` date DEFAULT NULL,
    `data_efetivacao` date NOT NULL,
    `data_aut_doc_fiscal` date DEFAULT NULL,
    `mes_efetivacao` varchar(10) CHARACTER SET utf8mb4 NOT NULL,
    `codigo_vendedor` int NOT NULL,
    `nome_vendedor` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
    `codigo_cliente` int DEFAULT NULL,
    `nome_cliente` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
    `codigo_produto` varchar(12) CHARACTER SET utf8mb4 NOT NULL,
    `ean` varchar(15) CHARACTER SET utf8mb4 DEFAULT NULL,
    `nome_produto` varchar(120) CHARACTER SET utf8mb4 NOT NULL,
    `fornecedor_1` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
    `fornecedor_2` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
    `fornecedor_3` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
    `fornecedor_4` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
    `fornecedor_5` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
    `fabricante` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
    `codigo_classe` int NOT NULL,
    `nome_classe` varchar(25) CHARACTER SET utf8mb4 NOT NULL,
    `codigo_familia` int DEFAULT NULL,
    `familia` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
    `quantidade` int DEFAULT NULL,
    `tabela_venda` varchar(20) CHARACTER SET utf8mb4 DEFAULT NULL,
    `tabela_comparativa_1` varchar(20) CHARACTER SET utf8mb4 DEFAULT NULL,
    `tabela_comparativa_2` varchar(20) CHARACTER SET utf8mb4 DEFAULT NULL,
    `preco_unitario` decimal(8, 2) NOT NULL,
    `valor_desconto` decimal(8, 2) NOT NULL DEFAULT '0.00',
    `percentual_desconto` decimal(7, 4) NOT NULL DEFAULT '0.0000',
    `valor_item_final` decimal(8, 2) NOT NULL,
    `valor_total_final` decimal(8, 2) DEFAULT NULL,
    `custo_item` decimal(8, 2) NOT NULL DEFAULT '0.00',
    `custo_total` decimal(8, 4) DEFAULT NULL,
    `markup_produto` decimal(7, 4) NOT NULL DEFAULT '0.0000',
    `markup_venda` decimal(7, 4) DEFAULT NULL,
    `margem_contribuicao_produto` decimal(8, 2) NOT NULL,
    `margem_contribuicao_venda` decimal(8, 2) DEFAULT NULL,
    `forma_recebimento` varchar(150) CHARACTER SET utf8mb4 DEFAULT NULL,
    `quantidade_parcelas` int DEFAULT NULL,
    `ano` int NOT NULL,
    `mes` int NOT NULL,
    `dia` int NOT NULL,
    `margem` decimal(8, 2) NOT NULL,
    `valor_carne` decimal(8, 2) DEFAULT NULL,
    `valor_dinheiro` decimal(8, 2) DEFAULT NULL,
    `valor_cartao_credito` decimal(8, 2) DEFAULT NULL,
    `valor_cartao_debito` decimal(8, 2) DEFAULT NULL,
    `valor_troca` decimal(8, 2) DEFAULT NULL,
    `valor_cartao_convenio` decimal(8, 2) DEFAULT NULL,
    `valor_carteira` decimal(8, 2) DEFAULT NULL,
    `valor_credito` decimal(8, 2) DEFAULT NULL,
    `marca` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
    `modelo` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
    `tipo_lente` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
    `indice` varchar(25) CHARACTER SET utf8mb4 DEFAULT NULL,
    `tratamento_foto` varchar(25) CHARACTER SET utf8mb4 DEFAULT NULL,
    `tratamento_ar` varchar(25) CHARACTER SET utf8mb4 DEFAULT NULL,
    `variacao_ar` varchar(25) CHARACTER SET utf8mb4 DEFAULT NULL,
    `esferico` decimal(4, 2) DEFAULT NULL,
    `cilindrico` decimal(4, 2) DEFAULT NULL,
    `eixo` int DEFAULT NULL,
    PRIMARY KEY (`id`)
  )")

